### ISSUE TITLE
请问如何使用？

### ISSUE THREAD

**Issue by DumoeDss** [theGravityLab/Onebot.Net#2]
你好，我想要制作一个基于Onebot协议的本地机器人客户端（非QQ机器人），配合nonebot2的onebot适配器使用。
但是我对于Onebot不太了解，目前查到的Onebot相关的信息都是QQ机器人，请问如果是基于该库制作Onebot客户端的话应该怎么操作呢？
我看nonebot2的websocket驱动器是作为websocket的客户端，而该库也是作为websocket的客户端，所以不清楚要怎么使用该库。

**Comment by d3ara1n** [comment]
这个库是dotnet平台的的onebotv12协议，nonebot用的python。请移步到[nonebot官方文档](https://v2.nonebot.dev/)进一步查询

**Comment by DumoeDss** [comment]
emmmmm，单纯对本库的使用，是需要有一个onebot的服务器端对吗？

**Comment by d3ara1n** [comment]
是的，而且是onebot12。目前onebot12服务端只有walleq支持。

**Comment by d3ara1n** [comment]
是的，这个是onebotv12客户端。服务端是针对平台的，qq的有walleq，特殊需求需要自己实现onebot文档定义的接口的服务端。

本库包含onebot一般数据结构（适用于客户服务端），反序列化（json，适用于客户端），数据收发（websocket，主动连接，适用于客户端）。我会在未来把后两个拆到其他包。如果要写服务端得自己实现后两个即序列化和websocket被动连接。
