### ISSUE TITLE
这个现在还能用吗，还是基于原来网页版本的 ？

### ISSUE THREAD

**Issue by alivy** [theGravityLab/Onebot.Net#3]
除了配置一个Websocket，配置机器人的信息在哪里配置呢？好像并没有操作成功

**Comment by d3ara1n** [comment]
基于OnebotV11，与三年前的Mirai和Gocqhttp有着完美的兼容性（就是为了这俩接口写的）。
但是，上次更新3 years ago，早就年久失修了。现在Onebot也不是主流了，不知道接口变了没。要用的话去找找别的，我也没精力维护这个项目。
